# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/danil/Desktop/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/danil/Desktop/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danil/Desktop/eschalot-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danil/Desktop/eschalot-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/danil/Desktop/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/danil/Desktop/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danil/Desktop/eschalot-master/CMakeFiles /home/danil/Desktop/eschalot-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danil/Desktop/eschalot-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named worgen

# Build rule for target.
worgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 worgen
.PHONY : worgen

# fast build rule for target.
worgen/fast:
	$(MAKE) -f CMakeFiles/worgen.dir/build.make CMakeFiles/worgen.dir/build
.PHONY : worgen/fast

#=============================================================================
# Target rules for targets named typecard

# Build rule for target.
typecard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 typecard
.PHONY : typecard

# fast build rule for target.
typecard/fast:
	$(MAKE) -f CMakeFiles/typecard.dir/build.make CMakeFiles/typecard.dir/build
.PHONY : typecard/fast

#=============================================================================
# Target rules for targets named eschalot

# Build rule for target.
eschalot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eschalot
.PHONY : eschalot

# fast build rule for target.
eschalot/fast:
	$(MAKE) -f CMakeFiles/eschalot.dir/build.make CMakeFiles/eschalot.dir/build
.PHONY : eschalot/fast

eschalot.o: eschalot.cpp.o

.PHONY : eschalot.o

# target to build an object file
eschalot.cpp.o:
	$(MAKE) -f CMakeFiles/eschalot.dir/build.make CMakeFiles/eschalot.dir/eschalot.cpp.o
.PHONY : eschalot.cpp.o

eschalot.i: eschalot.cpp.i

.PHONY : eschalot.i

# target to preprocess a source file
eschalot.cpp.i:
	$(MAKE) -f CMakeFiles/eschalot.dir/build.make CMakeFiles/eschalot.dir/eschalot.cpp.i
.PHONY : eschalot.cpp.i

eschalot.s: eschalot.cpp.s

.PHONY : eschalot.s

# target to generate assembly for a file
eschalot.cpp.s:
	$(MAKE) -f CMakeFiles/eschalot.dir/build.make CMakeFiles/eschalot.dir/eschalot.cpp.s
.PHONY : eschalot.cpp.s

typecard.o: typecard.cpp.o

.PHONY : typecard.o

# target to build an object file
typecard.cpp.o:
	$(MAKE) -f CMakeFiles/typecard.dir/build.make CMakeFiles/typecard.dir/typecard.cpp.o
.PHONY : typecard.cpp.o

typecard.i: typecard.cpp.i

.PHONY : typecard.i

# target to preprocess a source file
typecard.cpp.i:
	$(MAKE) -f CMakeFiles/typecard.dir/build.make CMakeFiles/typecard.dir/typecard.cpp.i
.PHONY : typecard.cpp.i

typecard.s: typecard.cpp.s

.PHONY : typecard.s

# target to generate assembly for a file
typecard.cpp.s:
	$(MAKE) -f CMakeFiles/typecard.dir/build.make CMakeFiles/typecard.dir/typecard.cpp.s
.PHONY : typecard.cpp.s

worgen.o: worgen.cpp.o

.PHONY : worgen.o

# target to build an object file
worgen.cpp.o:
	$(MAKE) -f CMakeFiles/worgen.dir/build.make CMakeFiles/worgen.dir/worgen.cpp.o
.PHONY : worgen.cpp.o

worgen.i: worgen.cpp.i

.PHONY : worgen.i

# target to preprocess a source file
worgen.cpp.i:
	$(MAKE) -f CMakeFiles/worgen.dir/build.make CMakeFiles/worgen.dir/worgen.cpp.i
.PHONY : worgen.cpp.i

worgen.s: worgen.cpp.s

.PHONY : worgen.s

# target to generate assembly for a file
worgen.cpp.s:
	$(MAKE) -f CMakeFiles/worgen.dir/build.make CMakeFiles/worgen.dir/worgen.cpp.s
.PHONY : worgen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... worgen"
	@echo "... typecard"
	@echo "... edit_cache"
	@echo "... eschalot"
	@echo "... eschalot.o"
	@echo "... eschalot.i"
	@echo "... eschalot.s"
	@echo "... typecard.o"
	@echo "... typecard.i"
	@echo "... typecard.s"
	@echo "... worgen.o"
	@echo "... worgen.i"
	@echo "... worgen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

